---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  - tcproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.nhn.no
  resources:
  - gslbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.nhn.no
  resources:
  - gslbservices/finalizers
  verbs:
  - update
- apiGroups:
  - lb.nhn.no
  resources:
  - gslbservices/status
  verbs:
  - get
  - patch
  - update
